# Site settings
title: Momo's Space
email: tomboy17@163.com
description: > # this means to ignore newlines until "baseurl:"
  Hey...Ho...Let's go...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://litongxin.github.io" # the base hostname & protocol for your site
github_username:  litongxin

# Build settings
markdown: kramdown
